### ISSUE TITLE
Callback should be called multiple times

### ISSUE THREAD

**Issue by miloskrca** [AOEpeople/deferred-event-callback#2]
In test:
https://github.com/AOEpeople/deferred-event-callback/blob/master/spec/phantomjs/callbackCallingSpec.js#L42
the callback should be executed 3 times.

Here: https://github.com/AOEpeople/deferred-event-callback/blob/master/deferred-event-callback.js#L42
the previously scheduled callbacks are terminated by the next callback so I suspect only the last callback actually gets executed.

**Comment by mdix** [comment]
Hey @miloskrca,

this is not how it's indented to work. The callback should only be triggered once, even if multiple events and nodes are used. E. g. [this test](https://github.com/AOEpeople/deferred-event-callback/blob/f241942968e1ad8f38c799d72fde01f51c524f19/spec/phantomjs/callbackCallingJquerySpec.js#L47).

I changed some stuff according to our conversation. Please check the [CHANGELOG](https://github.com/AOEpeople/deferred-event-callback/blob/master/CHANGELOG.md). I'd also happy if you'd migrate from 5.3.0 to 6.0.0 and if you could let me know if everything went well.
